SELECT pool_versions.id,
       pool_versions.pool_id,
       pool_versions.post_ids,
       pool_versions.added_post_ids,
       pool_versions.removed_post_ids,
       pool_versions.updater_id,
       pool_versions.description,
       pool_versions.description_changed,
       pool_versions.name,
       pool_versions.name_changed,
       pool_versions.created_at,
       pool_versions.updated_at,
       pool_versions.is_ongoing,
       pool_versions.is_ongoing_changed,
       pool_versions.version
FROM public.pool_versions ORDER BY pool_versions.id ASC
